### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by kamrancr7** [aldiferdiyan/flutter_xmpp#2]
Application is not connecting to my server following is the log:

```
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device CPH1819...
I/flutter (15039): DISCONNECTED

```

**Comment by kamrancr7** [comment]
now it is showing me the following error:

```
D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
W/System.err: org.jivesoftware.smack.SmackException$SecurityRequiredByServerException: SSL/TLS required by server but disabled in client
W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection.afterFeaturesReceived(XMPPTCPConnection.java:948)
        at org.jivesoftware.smack.AbstractXMPPConnection.parseFeatures(AbstractXMPPConnection.java:1514)
W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1100(XMPPTCPConnection.java:151)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1066)
W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:764)
W/AbstractXMPPConnection: Connection XMPPTCPConnection[not-authenticated] (0) closed with error
    org.jivesoftware.smack.SmackException$SecurityRequiredByServerException: SSL/TLS required by server but disabled in client
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.afterFeaturesReceived(XMPPTCPConnection.java:948)
        at org.jivesoftware.smack.AbstractXMPPConnection.parseFeatures(AbstractXMPPConnection.java:1514)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1100(XMPPTCPConnection.java:151)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1066)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:764)
D/flutter_xmpp: ConnectionClosedOnError, error org.jivesoftware.smack.SmackException$SecurityRequiredByServerException: SSL/TLS required by server but disabled in client
D/flutter_xmpp: Connectionclosed()
I/flutter: DISCONNECTED
D/flutter_xmpp: Current Status : DISCONNECTED
D/flutter_xmpp: Current Status : DISCONNECTED
W/Choreographer: Frame time is 7.596155 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
I/flutter: SystemChannels> AppLifecycleState.inactive
I/flutter: SystemChannels> AppLifecycleState.paused
I/Choreographer: Skipped 2 frames!  The application may be doing too much work on its main thread.
```

**Comment by MounirSd** [comment]
Any solution regarding `SSL/TLS required by server but disabled in client` issue?

**Comment by GhabrielFiorotti** [comment]
Alguma solução?
